### ISSUE TITLE
Day 10 - Part 2 - Need to sort results before selecting middle value?

### ISSUE THREAD

**Issue by l-rettberg** [Frugghi/Advent-of-Code-2021#1]
Enjoying reviewing your code strategy and style!

Seems like (for me at least) that for Day 10 - Part 2 - I needed to sort the resulting array prior to picking the middle value?

**Comment by Frugghi** [comment]
Thanks, I'm glad you enjoy my solutions!

I forgot to sort the array indeed! I guess I didn't notice because the result for my input was already in the middle :)

**Comment by Frugghi** [comment]
Fixed! Thank you for reporting the issue.

**Comment by l-rettberg** [comment]
Glad to help!
Best Regards!
